-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local client2gate_msg_type_pb = require("client2gate_msg_type_pb")
local msg_type_def_pb = require("msg_type_def_pb")
module('client2gate_protocol_pb')


PACKETC2G_HEARTBEAT = protobuf.Descriptor();
local PACKETC2G_HEARTBEAT_PACKET_ID_FIELD = protobuf.FieldDescriptor();
MSG_PACKET = protobuf.Descriptor();
local MSG_PACKET_MSGID_FIELD = protobuf.FieldDescriptor();
local MSG_PACKET_MSGINFO_FIELD = protobuf.FieldDescriptor();
PACKET_G2C_SEND_MSGLIST = protobuf.Descriptor();
local PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD = protobuf.FieldDescriptor();
local PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD = protobuf.FieldDescriptor();
PACKETC2G_SELECT_GATE = protobuf.Descriptor();
local PACKETC2G_SELECT_GATE_PACKET_ID_FIELD = protobuf.FieldDescriptor();
PACKETG2C_SELECT_GATE_RESULT = protobuf.Descriptor();
local PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD = protobuf.FieldDescriptor();
local PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD = protobuf.FieldDescriptor();
local PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD = protobuf.FieldDescriptor();
local PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD = protobuf.FieldDescriptor();

PACKETC2G_HEARTBEAT_PACKET_ID_FIELD.name = "packet_id"
PACKETC2G_HEARTBEAT_PACKET_ID_FIELD.full_name = ".client2gate_protocols.packetc2g_heartbeat.packet_id"
PACKETC2G_HEARTBEAT_PACKET_ID_FIELD.number = 1
PACKETC2G_HEARTBEAT_PACKET_ID_FIELD.index = 0
PACKETC2G_HEARTBEAT_PACKET_ID_FIELD.label = 1
PACKETC2G_HEARTBEAT_PACKET_ID_FIELD.enum_type = client2gate_msg_type_pb.E_SERVER_MSG_TYPE
PACKETC2G_HEARTBEAT_PACKET_ID_FIELD.has_default_value = true
PACKETC2G_HEARTBEAT_PACKET_ID_FIELD.default_value = client2gate_msg_type_pb.e_mst_c2g_heartbeat
PACKETC2G_HEARTBEAT_PACKET_ID_FIELD.type = 14
PACKETC2G_HEARTBEAT_PACKET_ID_FIELD.cpp_type = 8

PACKETC2G_HEARTBEAT.name = "packetc2g_heartbeat"
PACKETC2G_HEARTBEAT.full_name = ".client2gate_protocols.packetc2g_heartbeat"
PACKETC2G_HEARTBEAT.nested_types = {}
PACKETC2G_HEARTBEAT.enum_types = {}
PACKETC2G_HEARTBEAT.fields = {PACKETC2G_HEARTBEAT_PACKET_ID_FIELD}
PACKETC2G_HEARTBEAT.is_extendable = false
PACKETC2G_HEARTBEAT.extensions = {}
MSG_PACKET_MSGID_FIELD.name = "msgid"
MSG_PACKET_MSGID_FIELD.full_name = ".client2gate_protocols.msg_packet.msgid"
MSG_PACKET_MSGID_FIELD.number = 1
MSG_PACKET_MSGID_FIELD.index = 0
MSG_PACKET_MSGID_FIELD.label = 1
MSG_PACKET_MSGID_FIELD.has_default_value = false
MSG_PACKET_MSGID_FIELD.default_value = 0
MSG_PACKET_MSGID_FIELD.type = 5
MSG_PACKET_MSGID_FIELD.cpp_type = 1

MSG_PACKET_MSGINFO_FIELD.name = "msginfo"
MSG_PACKET_MSGINFO_FIELD.full_name = ".client2gate_protocols.msg_packet.msginfo"
MSG_PACKET_MSGINFO_FIELD.number = 2
MSG_PACKET_MSGINFO_FIELD.index = 1
MSG_PACKET_MSGINFO_FIELD.label = 1
MSG_PACKET_MSGINFO_FIELD.has_default_value = false
MSG_PACKET_MSGINFO_FIELD.default_value = ""
MSG_PACKET_MSGINFO_FIELD.type = 12
MSG_PACKET_MSGINFO_FIELD.cpp_type = 9

MSG_PACKET.name = "msg_packet"
MSG_PACKET.full_name = ".client2gate_protocols.msg_packet"
MSG_PACKET.nested_types = {}
MSG_PACKET.enum_types = {}
MSG_PACKET.fields = {MSG_PACKET_MSGID_FIELD, MSG_PACKET_MSGINFO_FIELD}
MSG_PACKET.is_extendable = false
MSG_PACKET.extensions = {}
PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD.name = "packet_id"
PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD.full_name = ".client2gate_protocols.packet_g2c_send_msglist.packet_id"
PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD.number = 1
PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD.index = 0
PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD.label = 1
PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD.enum_type = client2gate_msg_type_pb.E_SERVER_MSG_TYPE
PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD.has_default_value = true
PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD.default_value = client2gate_msg_type_pb.e_mst_g2c_send_msglist
PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD.type = 14
PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD.cpp_type = 8

PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD.name = "msgpaks"
PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD.full_name = ".client2gate_protocols.packet_g2c_send_msglist.msgpaks"
PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD.number = 3
PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD.index = 1
PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD.label = 3
PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD.message_type = MSG_PACKET
PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD.has_default_value = false
PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD.default_value = {}
PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD.type = 11
PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD.cpp_type = 10

PACKET_G2C_SEND_MSGLIST.name = "packet_g2c_send_msglist"
PACKET_G2C_SEND_MSGLIST.full_name = ".client2gate_protocols.packet_g2c_send_msglist"
PACKET_G2C_SEND_MSGLIST.nested_types = {}
PACKET_G2C_SEND_MSGLIST.enum_types = {}
PACKET_G2C_SEND_MSGLIST.fields = {PACKET_G2C_SEND_MSGLIST_PACKET_ID_FIELD, PACKET_G2C_SEND_MSGLIST_MSGPAKS_FIELD}
PACKET_G2C_SEND_MSGLIST.is_extendable = false
PACKET_G2C_SEND_MSGLIST.extensions = {}
PACKETC2G_SELECT_GATE_PACKET_ID_FIELD.name = "packet_id"
PACKETC2G_SELECT_GATE_PACKET_ID_FIELD.full_name = ".client2gate_protocols.packetc2g_select_gate.packet_id"
PACKETC2G_SELECT_GATE_PACKET_ID_FIELD.number = 1
PACKETC2G_SELECT_GATE_PACKET_ID_FIELD.index = 0
PACKETC2G_SELECT_GATE_PACKET_ID_FIELD.label = 1
PACKETC2G_SELECT_GATE_PACKET_ID_FIELD.enum_type = client2gate_msg_type_pb.E_SERVER_MSG_TYPE
PACKETC2G_SELECT_GATE_PACKET_ID_FIELD.has_default_value = true
PACKETC2G_SELECT_GATE_PACKET_ID_FIELD.default_value = client2gate_msg_type_pb.e_mst_c2g_select_gate
PACKETC2G_SELECT_GATE_PACKET_ID_FIELD.type = 14
PACKETC2G_SELECT_GATE_PACKET_ID_FIELD.cpp_type = 8

PACKETC2G_SELECT_GATE.name = "packetc2g_select_gate"
PACKETC2G_SELECT_GATE.full_name = ".client2gate_protocols.packetc2g_select_gate"
PACKETC2G_SELECT_GATE.nested_types = {}
PACKETC2G_SELECT_GATE.enum_types = {}
PACKETC2G_SELECT_GATE.fields = {PACKETC2G_SELECT_GATE_PACKET_ID_FIELD}
PACKETC2G_SELECT_GATE.is_extendable = false
PACKETC2G_SELECT_GATE.extensions = {}
PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD.name = "packet_id"
PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD.full_name = ".client2gate_protocols.packetg2c_select_gate_result.packet_id"
PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD.number = 1
PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD.index = 0
PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD.label = 1
PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD.enum_type = client2gate_msg_type_pb.E_SERVER_MSG_TYPE
PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD.has_default_value = true
PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD.default_value = client2gate_msg_type_pb.e_mst_g2c_select_gate_result
PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD.type = 14
PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD.cpp_type = 8

PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD.name = "result"
PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD.full_name = ".client2gate_protocols.packetg2c_select_gate_result.result"
PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD.number = 2
PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD.index = 1
PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD.label = 1
PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD.enum_type = msg_type_def_pb.E_MSG_RESULT_DEF
PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD.has_default_value = true
PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD.default_value = msg_type_def_pb.e_rmt_success
PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD.type = 14
PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD.cpp_type = 8

PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD.name = "new_ip"
PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD.full_name = ".client2gate_protocols.packetg2c_select_gate_result.new_ip"
PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD.number = 3
PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD.index = 2
PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD.label = 1
PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD.has_default_value = false
PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD.default_value = ""
PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD.type = 9
PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD.cpp_type = 9

PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD.name = "new_port"
PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD.full_name = ".client2gate_protocols.packetg2c_select_gate_result.new_port"
PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD.number = 4
PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD.index = 3
PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD.label = 1
PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD.has_default_value = false
PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD.default_value = 0
PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD.type = 5
PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD.cpp_type = 1

PACKETG2C_SELECT_GATE_RESULT.name = "packetg2c_select_gate_result"
PACKETG2C_SELECT_GATE_RESULT.full_name = ".client2gate_protocols.packetg2c_select_gate_result"
PACKETG2C_SELECT_GATE_RESULT.nested_types = {}
PACKETG2C_SELECT_GATE_RESULT.enum_types = {}
PACKETG2C_SELECT_GATE_RESULT.fields = {PACKETG2C_SELECT_GATE_RESULT_PACKET_ID_FIELD, PACKETG2C_SELECT_GATE_RESULT_RESULT_FIELD, PACKETG2C_SELECT_GATE_RESULT_NEW_IP_FIELD, PACKETG2C_SELECT_GATE_RESULT_NEW_PORT_FIELD}
PACKETG2C_SELECT_GATE_RESULT.is_extendable = false
PACKETG2C_SELECT_GATE_RESULT.extensions = {}

msg_packet = protobuf.Message(MSG_PACKET)
packet_g2c_send_msglist = protobuf.Message(PACKET_G2C_SEND_MSGLIST)
packetc2g_heartbeat = protobuf.Message(PACKETC2G_HEARTBEAT)
packetc2g_select_gate = protobuf.Message(PACKETC2G_SELECT_GATE)
packetg2c_select_gate_result = protobuf.Message(PACKETG2C_SELECT_GATE_RESULT)

