-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local client2world_msg_type_pb = require("client2world_msg_type_pb")
local msg_type_def_pb = require("msg_type_def_pb")
local msg_info_def_pb = require("msg_info_def_pb")
module('client2world_notice_pb')


PACKETC2W_REQ_NOTICE = protobuf.Descriptor();
local PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD = protobuf.FieldDescriptor();
local PACKETC2W_REQ_NOTICE_LASTTIME_FIELD = protobuf.FieldDescriptor();
NOTICEINFO = protobuf.Descriptor();
local NOTICEINFO_GENTIME_FIELD = protobuf.FieldDescriptor();
local NOTICEINFO_TITLE_FIELD = protobuf.FieldDescriptor();
local NOTICEINFO_CONTENT_FIELD = protobuf.FieldDescriptor();
local NOTICEINFO_ORDER_FIELD = protobuf.FieldDescriptor();
PACKETW2C_REQ_NOTICE_RESULT = protobuf.Descriptor();
local PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD = protobuf.FieldDescriptor();
local PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD = protobuf.FieldDescriptor();
local PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD = protobuf.FieldDescriptor();

PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD.name = "packet_id"
PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD.full_name = ".client2world_protocols.packetc2w_req_notice.packet_id"
PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD.number = 1
PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD.index = 0
PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD.label = 1
PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD.enum_type = client2world_msg_type_pb.E_SERVER_MSG_TYPE
PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD.has_default_value = true
PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD.default_value = client2world_msg_type_pb.e_mst_c2w_req_notice
PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD.type = 14
PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD.cpp_type = 8

PACKETC2W_REQ_NOTICE_LASTTIME_FIELD.name = "lastTime"
PACKETC2W_REQ_NOTICE_LASTTIME_FIELD.full_name = ".client2world_protocols.packetc2w_req_notice.lastTime"
PACKETC2W_REQ_NOTICE_LASTTIME_FIELD.number = 2
PACKETC2W_REQ_NOTICE_LASTTIME_FIELD.index = 1
PACKETC2W_REQ_NOTICE_LASTTIME_FIELD.label = 1
PACKETC2W_REQ_NOTICE_LASTTIME_FIELD.has_default_value = false
PACKETC2W_REQ_NOTICE_LASTTIME_FIELD.default_value = 0
PACKETC2W_REQ_NOTICE_LASTTIME_FIELD.type = 5
PACKETC2W_REQ_NOTICE_LASTTIME_FIELD.cpp_type = 1

PACKETC2W_REQ_NOTICE.name = "packetc2w_req_notice"
PACKETC2W_REQ_NOTICE.full_name = ".client2world_protocols.packetc2w_req_notice"
PACKETC2W_REQ_NOTICE.nested_types = {}
PACKETC2W_REQ_NOTICE.enum_types = {}
PACKETC2W_REQ_NOTICE.fields = {PACKETC2W_REQ_NOTICE_PACKET_ID_FIELD, PACKETC2W_REQ_NOTICE_LASTTIME_FIELD}
PACKETC2W_REQ_NOTICE.is_extendable = false
PACKETC2W_REQ_NOTICE.extensions = {}
NOTICEINFO_GENTIME_FIELD.name = "genTime"
NOTICEINFO_GENTIME_FIELD.full_name = ".client2world_protocols.NoticeInfo.genTime"
NOTICEINFO_GENTIME_FIELD.number = 1
NOTICEINFO_GENTIME_FIELD.index = 0
NOTICEINFO_GENTIME_FIELD.label = 1
NOTICEINFO_GENTIME_FIELD.has_default_value = false
NOTICEINFO_GENTIME_FIELD.default_value = 0
NOTICEINFO_GENTIME_FIELD.type = 5
NOTICEINFO_GENTIME_FIELD.cpp_type = 1

NOTICEINFO_TITLE_FIELD.name = "title"
NOTICEINFO_TITLE_FIELD.full_name = ".client2world_protocols.NoticeInfo.title"
NOTICEINFO_TITLE_FIELD.number = 2
NOTICEINFO_TITLE_FIELD.index = 1
NOTICEINFO_TITLE_FIELD.label = 1
NOTICEINFO_TITLE_FIELD.has_default_value = false
NOTICEINFO_TITLE_FIELD.default_value = ""
NOTICEINFO_TITLE_FIELD.type = 9
NOTICEINFO_TITLE_FIELD.cpp_type = 9

NOTICEINFO_CONTENT_FIELD.name = "content"
NOTICEINFO_CONTENT_FIELD.full_name = ".client2world_protocols.NoticeInfo.content"
NOTICEINFO_CONTENT_FIELD.number = 3
NOTICEINFO_CONTENT_FIELD.index = 2
NOTICEINFO_CONTENT_FIELD.label = 1
NOTICEINFO_CONTENT_FIELD.has_default_value = false
NOTICEINFO_CONTENT_FIELD.default_value = ""
NOTICEINFO_CONTENT_FIELD.type = 9
NOTICEINFO_CONTENT_FIELD.cpp_type = 9

NOTICEINFO_ORDER_FIELD.name = "order"
NOTICEINFO_ORDER_FIELD.full_name = ".client2world_protocols.NoticeInfo.order"
NOTICEINFO_ORDER_FIELD.number = 4
NOTICEINFO_ORDER_FIELD.index = 3
NOTICEINFO_ORDER_FIELD.label = 1
NOTICEINFO_ORDER_FIELD.has_default_value = false
NOTICEINFO_ORDER_FIELD.default_value = 0
NOTICEINFO_ORDER_FIELD.type = 5
NOTICEINFO_ORDER_FIELD.cpp_type = 1

NOTICEINFO.name = "NoticeInfo"
NOTICEINFO.full_name = ".client2world_protocols.NoticeInfo"
NOTICEINFO.nested_types = {}
NOTICEINFO.enum_types = {}
NOTICEINFO.fields = {NOTICEINFO_GENTIME_FIELD, NOTICEINFO_TITLE_FIELD, NOTICEINFO_CONTENT_FIELD, NOTICEINFO_ORDER_FIELD}
NOTICEINFO.is_extendable = false
NOTICEINFO.extensions = {}
PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD.name = "packet_id"
PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD.full_name = ".client2world_protocols.packetw2c_req_notice_result.packet_id"
PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD.number = 1
PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD.index = 0
PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD.label = 1
PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD.enum_type = client2world_msg_type_pb.E_SERVER_MSG_TYPE
PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD.has_default_value = true
PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD.default_value = client2world_msg_type_pb.e_mst_w2c_req_notice_result
PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD.type = 14
PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD.cpp_type = 8

PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD.name = "infoList"
PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD.full_name = ".client2world_protocols.packetw2c_req_notice_result.infoList"
PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD.number = 2
PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD.index = 1
PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD.label = 3
PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD.message_type = NOTICEINFO
PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD.has_default_value = false
PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD.default_value = {}
PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD.type = 11
PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD.cpp_type = 10

PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD.name = "lastTime"
PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD.full_name = ".client2world_protocols.packetw2c_req_notice_result.lastTime"
PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD.number = 3
PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD.index = 2
PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD.label = 1
PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD.has_default_value = false
PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD.default_value = 0
PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD.type = 5
PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD.cpp_type = 1

PACKETW2C_REQ_NOTICE_RESULT.name = "packetw2c_req_notice_result"
PACKETW2C_REQ_NOTICE_RESULT.full_name = ".client2world_protocols.packetw2c_req_notice_result"
PACKETW2C_REQ_NOTICE_RESULT.nested_types = {}
PACKETW2C_REQ_NOTICE_RESULT.enum_types = {}
PACKETW2C_REQ_NOTICE_RESULT.fields = {PACKETW2C_REQ_NOTICE_RESULT_PACKET_ID_FIELD, PACKETW2C_REQ_NOTICE_RESULT_INFOLIST_FIELD, PACKETW2C_REQ_NOTICE_RESULT_LASTTIME_FIELD}
PACKETW2C_REQ_NOTICE_RESULT.is_extendable = false
PACKETW2C_REQ_NOTICE_RESULT.extensions = {}

NoticeInfo = protobuf.Message(NOTICEINFO)
packetc2w_req_notice = protobuf.Message(PACKETC2W_REQ_NOTICE)
packetw2c_req_notice_result = protobuf.Message(PACKETW2C_REQ_NOTICE_RESULT)

